### ISSUE TITLE
Mapply randomly breaks

### ISSUE THREAD

**Issue by thoughtfuldata** [ddelange/mapply#17]
#### What you were trying to do (and why)

System information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 : 10.0.19041
    Mapply Version: 0.1.9
    Python version: 3.9.6

I am attempting to use mapply with a custom function across many little dataframes. The custom function makes an API call to an outside server. The call below is inside a for loop that splits a larger dataframe into 500 row dataframes

#### What happened (including reproducible example)

<details><summary>Reproducible example</summary><p>

Initially the code work(for 56 of the small data frames) but then I am given an error

this is how the large pandas data frame(transcript_df) looks like

videoID
0	FfgT6zx4k3Q
1	fBxtS9BpVWs
2	uqKGREZs6-w
3	1rb3bMvDdX4
4	ulCdoCfw-bY
...	...
566826	vhgawlCAKCM
566827	ej8s6XZ93VI
566828	6r7n1D8Memc
566829	Hl8FROYN9IM
566830	nQxoVw_gZJQ

```py
n = 500
proc_dfs = []

for i in range(0, len(transcript_df), n):
    print(I)
	temp_df = transcript_df.iloc[i:i + n].copy()
    temp_df['transcripts'] = temp_df.mapply(get_transcripts, axis=1)
    proc_dfs.append(temp_df)

```

```
0
100%|██████████| 500/500 [02:02<00:00,  4.07it/s]
500
100%|██████████| 500/500 [02:03<00:00,  4.06it/s]
1000
100%|██████████| 500/500 [02:04<00:00,  4.02it/s]
1500
100%|██████████| 500/500 [02:01<00:00,  4.12it/s]
2000
100%|██████████| 500/500 [02:01<00:00,  4.12it/s]
2500
100%|██████████| 500/500 [02:02<00:00,  4.09it/s]
3000
100%|██████████| 500/500 [01:58<00:00,  4.24it/s]
3500
100%|██████████| 500/500 [01:42<00:00,  4.90it/s]
4000
100%|██████████| 500/500 [02:02<00:00,  4.08it/s]
4500
100%|██████████| 500/500 [02:00<00:00,  4.13it/s]
5000
100%|██████████| 500/500 [02:01<00:00,  4.12it/s]
5500
100%|██████████| 500/500 [02:00<00:00,  4.16it/s]
6000
100%|██████████| 500/500 [01:58<00:00,  4.21it/s]
6500
100%|██████████| 500/500 [01:56<00:00,  4.31it/s]
7000
100%|██████████| 500/500 [01:58<00:00,  4.23it/s]
7500
100%|██████████| 500/500 [01:58<00:00,  4.23it/s]
8000
100%|██████████| 500/500 [01:55<00:00,  4.32it/s]
8500
100%|██████████| 500/500 [01:54<00:00,  4.37it/s]
9000
100%|██████████| 500/500 [01:54<00:00,  4.38it/s]
9500
100%|██████████| 500/500 [01:57<00:00,  4.25it/s]
10000
100%|██████████| 500/500 [01:57<00:00,  4.26it/s]
10500
100%|██████████| 500/500 [01:57<00:00,  4.25it/s]
11000
100%|██████████| 500/500 [01:58<00:00,  4.23it/s]
11500
100%|██████████| 500/500 [01:55<00:00,  4.32it/s]
12000
100%|██████████| 500/500 [02:02<00:00,  4.09it/s]
12500
100%|██████████| 500/500 [01:59<00:00,  4.17it/s]
13000
100%|██████████| 500/500 [01:59<00:00,  4.18it/s]
13500
100%|██████████| 500/500 [01:56<00:00,  4.31it/s]
14000
100%|██████████| 500/500 [01:55<00:00,  4.34it/s]
14500
100%|██████████| 500/500 [01:54<00:00,  4.35it/s]
15000
100%|██████████| 500/500 [01:55<00:00,  4.35it/s]
15500
100%|██████████| 500/500 [01:55<00:00,  4.33it/s]
16000
100%|██████████| 500/500 [01:56<00:00,  4.30it/s]
16500
100%|██████████| 500/500 [01:54<00:00,  4.35it/s]
17000
100%|██████████| 500/500 [01:52<00:00,  4.45it/s]
17500
100%|██████████| 500/500 [01:53<00:00,  4.40it/s]
18000
100%|██████████| 500/500 [01:56<00:00,  4.30it/s]
18500
100%|██████████| 500/500 [01:54<00:00,  4.37it/s]
19000
100%|██████████| 500/500 [01:56<00:00,  4.31it/s]
19500
100%|██████████| 500/500 [01:52<00:00,  4.44it/s]
20000
100%|██████████| 500/500 [01:53<00:00,  4.40it/s]
20500
100%|██████████| 500/500 [01:51<00:00,  4.50it/s]
21000
100%|██████████| 500/500 [01:55<00:00,  4.32it/s]
21500
100%|██████████| 500/500 [01:51<00:00,  4.48it/s]
22000
100%|██████████| 500/500 [01:50<00:00,  4.53it/s]
22500
100%|██████████| 500/500 [01:52<00:00,  4.43it/s]
23000
100%|██████████| 500/500 [01:56<00:00,  4.30it/s]
23500
100%|██████████| 500/500 [01:57<00:00,  4.25it/s]
24000
100%|██████████| 500/500 [01:55<00:00,  4.32it/s]
24500
100%|██████████| 500/500 [01:57<00:00,  4.24it/s]
25000
100%|██████████| 500/500 [01:53<00:00,  4.39it/s]
25500
100%|██████████| 500/500 [01:53<00:00,  4.41it/s]
26000
100%|██████████| 500/500 [01:55<00:00,  4.35it/s]
26500
100%|██████████| 500/500 [01:54<00:00,  4.36it/s]
27000
100%|██████████| 500/500 [01:57<00:00,  4.26it/s]
27500
100%|██████████| 500/500 [01:58<00:00,  4.23it/s]
28000
 77%|███████▋  | 386/500 [01:30<00:26,  4.24it/s]

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\multiprocess\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\pathos\helpers\mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\mapply\mapply.py", line 105, in run_apply
    return df_or_series.apply(func, args=args, **kwargs)
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\pandas\core\frame.py", line 8740, in apply
    return op.apply()
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\pandas\core\apply.py", line 688, in apply
    return self.apply_standard()
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\pandas\core\apply.py", line 812, in apply_standard
    results, res_index = self.apply_series_generator()
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\pandas\core\apply.py", line 828, in apply_series_generator
    results[i] = self.f(v)
  File "C:\Users\manue\AppData\Local\Temp/ipykernel_10772/780513497.py", line 5, in get_transcripts
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\youtube_transcript_api\_api.py", line 128, in get_transcript
    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\youtube_transcript_api\_api.py", line 70, in list_transcripts
    return TranscriptListFetcher(http_client).fetch(video_id)
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\youtube_transcript_api\_transcripts.py", line 36, in fetch
    self._extract_captions_json(self._fetch_video_html(video_id), video_id)
  File "c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\youtube_transcript_api\_transcripts.py", line 50, in _extract_captions_json
    captions_json = json.loads(
  File "C:\Users\manue\.pyenv\pyenv-win\versions\3.9.6\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\manue\.pyenv\pyenv-win\versions\3.9.6\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\manue\.pyenv\pyenv-win\versions\3.9.6\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 1576 (char 1575)
"""

The above exception was the direct cause of the following exception:

JSONDecodeError                           Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_10772/3199509052.py in <module>
      9     #    lower = round((len(transcript_df) / splits) * i)
     10     #    upper = round((len(transcript_df) / splits) * (i + 1))
---> 11     temp_df['transcripts'] = temp_df.mapply(get_transcripts, axis=1)
     12     #print(temp_df)
     13     proc_dfs.append(temp_df)

c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\mapply\mapply.py in mapply(df_or_series, func, axis, n_workers, chunk_size, max_chunks_per_worker, progressbar, args, **kwargs)
    108         kwargs["axis"] = axis
    109 
--> 110     results = multiprocessing_imap(
    111         partial(run_apply, func, args=args, **kwargs),
    112         dfs,

c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\mapply\parallel.py in multiprocessing_imap(func, iterable, n_workers, progressbar, args, **kwargs)
    101 
    102     try:
--> 103         return list(stage)
    104     except (Exception, KeyboardInterrupt):
    105         if pool:

c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\tqdm\std.py in __iter__(self)
   1178 
   1179         try:
-> 1180             for obj in iterable:
   1181                 yield obj
   1182                 # Update and possibly print the progressbar.

c:\Users\manue\Documents\Github\data-science-venv\.venv\lib\site-packages\multiprocess\pool.py in next(self, timeout)
    868         if success:
    869             return value
--> 870         raise value
    871 
    872     __next__ = next                    # XXX

JSONDecodeError: Expecting ',' delimiter: line 1 column 1576 (char 1575)
```

#### What you expected to happen

I expected to work for each of the small data frames. I have ran individually the values where the error happens and they work fine

#### Step-by-step reproduction instructions

run code above (I have not provided the custom function,  but let me know if it is needed)

**Comment by ddelange** [comment]
Hi @thoughtfuldata,

This bug is not coming from mapply, but rather from the subprocess that mapply has spawned. See the `RemoteTraceback`.

My guess would be you bombed some server with too many concurrent requests, `_fetch_video_html` gave up and returned some 500 Internal Server Error or so response (some non-200 response which does not contain a payload and so can not be json decoded). Maybe they forgot to add a `response.raise_for_status()` which would have made this traceback more verbose.

My suggestion is to lower `n_workers` in order to treat the server more gracefully. If the next time the same error is thrown for the same row in your df (you can try to isolate by enabling `%pdb` ipython magic), it might just be an edge case server response which the writer of the library didn't account for.

Hope that helps!

**Comment by thoughtfuldata** [comment]
Got it, im new to multiprocessing, so it was unclear if it was an mapply issue or something internal. Thanks for the tip, I also added more feedback to the issue #11 .
