### ISSUE TITLE
Mapply lags after full progress bar

### ISSUE THREAD

**Issue by Floppa2003** [ddelange/mapply#58]
Hello again. I'm trying to use mapply to a dataframe consisting of about 200k rows:
```py
def convert_execution_period(row):
    contract_date = row[CONTRACT_DATE_COL]
    execution_period = row[EXECUTION_PERIOD_COL]
    data = applicator(contract_date, execution_period)
    return pd.Series(
        data=data,
        index=[EXECUTION_PERIOD_COL, "ContractDuration"],
    )

gp_df[[EXECUTION_PERIOD_COL, "ContractDuration"]] = gp_df[
        [CONTRACT_DATE_COL, EXECUTION_PERIOD_COL]
    ].mapply(convert_execution_period, axis=1)
<some other code after that>
```

<img width="926" alt="Снимок экрана 2023-12-11 в 5 32 36 PM" src="https://github.com/ddelange/mapply/assets/120779629/22e10a45-d7d3-4425-9da8-ee43cfc33820">

The calculation itself went pretty quickly (about 7 minutes), but after the progress bar completed nothing happened for about an hour or so, so I killed the process manually. As it can be seen from the screenshot, the program was stuck on the stage of joining results computed by the cores (anyway it's what I think based on the stacktrace). My mapply is of the latest version and there were no other heavy processes running on my computer but I'm worried that it happens because my function returns a pd.Series instead of a single object, because the usage of mapply on a single column just above this case went successfully. The problem didn't appear when I set n_workers equal to 1 (and appeared when I set it to 4 or 8). Should I rewrite the code so that it modifies one column at a time or is the problem somewhere else?

**Comment by ddelange** [comment]
Hi :wave:

Sounds like either something specific to your system and/or your code that's run in apply (similar to #42).

Can you try the example from the mapply docs with 200k rows? To eliminate the former?

And to eliminate the latter, can you try `import multiprocess; multiprocess.set_start_method("spawn")` and run your code snippet above again?

**Comment by ddelange** [comment]
There is another hidden setting that makes the `fork` start method (the default, the fastest, the most risky) more stable: https://github.com/ddelange/mapply/blob/0.1.22/src/mapply/parallel.py#L43

The lower the value, the more often a subprocess is replaced by a new one. Mostly needed for long running (like multiple hours) applies, and can be left alone.

But a long shot could be to set the env var to 1.

**Comment by Floppa2003** [comment]
I tried adding the `import multiprocess; multiprocess.set_start_method("spawn")` thing, but this led to an error:
<img width="1357" alt="Снимок экрана 2023-12-12 в 1 42 51 PM" src="https://github.com/ddelange/mapply/assets/120779629/91b12a78-d244-4034-9527-5d5879ca8d79">
By the way, if I have a project with multiple files, is it enough to initialize mapply only once in main? I import mapply in the main file and use it in functions imported from modules defined in another files - can this be the problem?

**Comment by ddelange** [comment]
Sorry, please add `force=True` and it should force the start method. Did you try the simple docs example with 200k rows, with the default start method? 

Regarding your second question: this is no problem, `mapply.init()` works on a global scope, no matter where/when you call it. It is unrelated to your error.

**Comment by ddelange** [comment]
btw, a general good practice for github/stackoverflow etc is to send code snippets (e.g. `` ```pytb``) instead of screenshots. less wasted bytes in the cloud, and it allows others find existing issues/questions/errors :)

**Comment by Floppa2003** [comment]
Tried it with force=True and the program started duplicating all output 4 times (because I set n_workers to 4) ending with an error
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/username/Desktop/new_processor/fdw_scoring/featurize_parser.py", line 134, in <module>
    ad_df = preprocess_ad(ad_df, feature_config)
  File "/Users/username/Desktop/new_processor/fdw_scoring/preprocessing/arbitration_defendant.py", line 82, in preprocess_ad
    ad_df["StatusAtApplicationDate"] = ad_df.mapply(
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/mapply/mapply.py", line 127, in mapply
    results = list(
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/mapply/parallel.py", line 101, in multiprocessing_imap
    pool = ProcessPool(n_workers, maxtasksperchild=MAX_TASKS_PER_CHILD)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pathos/multiprocessing.py", line 122, in __init__
    self._serve()
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pathos/multiprocessing.py", line 134, in _serve
    _pool = Pool(nodes, **self._kwds)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/multiprocess/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

Haven't tried the simple docs example yet.

**Comment by ddelange** [comment]
hmm, can you try `from multiprocess.context import _force_start_method; _force_start_method("spawn")` as early as possible?

**Comment by ddelange** [comment]
the docs example runs OK (with both start methods) on the colab 2 core environment: https://colab.research.google.com/drive/1Wtf2nKHjCkM_IVlNkO0-wfUV8zdw4WQS?usp=sharing

**Comment by ddelange** [comment]
hi 👋 release incoming to allow setting the start method in a proper way, see PR description:)
